apiVersion: v1
kind: Secret
metadata:
  name: app-data-secrets
  namespace: aks-learning
type: Opaque
stringData:
  products-sql-connection-string: "Driver={ODBC Driver 18 for SQL Server};Server=tcp:YOUR_SQLMI_FQDN,1433;Database=productsdb;Uid=sqladmin;Pwd=ChangeMe123!;Encrypt=yes;TrustServerCertificate=no;Connection Timeout=30;"
  orders-sql-connection-string: "Driver={ODBC Driver 18 for SQL Server};Server=tcp:YOUR_SQLMI_FQDN,1433;Database=ordersdb;Uid=sqladmin;Pwd=ChangeMe123!;Encrypt=yes;TrustServerCertificate=no;Connection Timeout=30;"
  orders-eventhub-connection-string: "Endpoint=sb://YOUR_EVENTHUB_NAMESPACE.servicebus.windows.net/;SharedAccessKeyName=orders-sender;SharedAccessKey=REPLACE_ME"
  orders-eventhub-name: "orders-events"
