apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: app-data-secrets-kv
  namespace: aks-learning
spec:
  provider: azure
  secretObjects:
    - secretName: app-data-secrets
      type: Opaque
      data:
        - objectName: products-sql-connection-string
          key: products-sql-connection-string
        - objectName: orders-sql-connection-string
          key: orders-sql-connection-string
        - objectName: orders-eventhub-connection-string
          key: orders-eventhub-connection-string
        - objectName: orders-eventhub-consumer-connection-string
          key: orders-eventhub-consumer-connection-string
        - objectName: orders-eventhub-name
          key: orders-eventhub-name
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: "645b75d6-83a1-4a98-b0d2-380065075a6d"
    keyvaultName: "kv-ecommerce-test-ic9b"
    tenantId: "5b973f99-77df-4beb-b27d-aa0c70b8482c"
    objects: |
      array:
        - |
          objectName: products-sql-connection-string
          objectType: secret
        - |
          objectName: orders-sql-connection-string
          objectType: secret
        - |
          objectName: orders-eventhub-connection-string
          objectType: secret
        - |
          objectName: orders-eventhub-consumer-connection-string
          objectType: secret
        - |
          objectName: orders-eventhub-name
          objectType: secret
