apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: aks-sample-ingress
  namespace: aks-learning
spec:
  ingressClassName: nginx
  rules:
    - host: 4.157.136.211.nip.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend
                port:
                  number: 80
